# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Slay-Maker
version:      0.05
version_from: lib/Slay/Maker.pm
installdirs:  site
requires:
    Class::Std:                    0
    IPC::Run:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
